### ISSUE TITLE
作业3中的问题：在Navigation和后面的内容之间多出很细（大概1px多）的一行空白

### ISSUE THREAD

**Issue by LiYingwei** [STU-Fudan/extra-home-work#14]
在Navigation和后面的内容之间多出很细（大概1px多）的一行空白，无法消除，即使把padding调成0也不行。
![2015-04-22 10 47 56](https://cloud.githubusercontent.com/assets/10908509/7266537/9e511026-e8dd-11e4-815c-6a6688133498.png)
index.html

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'/>
    <link href="index.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="wrapper">
        <img id="logo" src="Logo.gif" />
        <img id="search" src="Search.gif" />
        <img id="nav" src="Navigation.gif" />
        <img id="pic" src="pic.gif" />
        <img id="text" src="Text.gif" />
        <img id="fooer" src="Footer.gif" />
    </div>
</body>
```

index.css

``` css
#wrapper{
    width:720px;
    margin: 0 auto 0 auto;
}
#logo{
    float:left;
}
#search{
    float:right;
    margin-top:50px;
}
#nav{
    clear:both;
    padding-top:10px;
    padding-bottom:10px;
}
#pic{
    float:left;
    /*padding-top:10px;*/
    padding-right:10px;
}
#text{
    float:right;
    padding-bottom:10px;
}
#footer{
    float:right;
}
```
